### ISSUE TITLE
! could not find commit hash for master

### ISSUE THREAD

**Issue by jet10000** [kyrelldixon/svelte-tailwind-extension-boilerplate#1]
```
 npx degit kyrelldixon/svelte-tailwind-extension-boilerplate
! could not find commit hash for master

node -v
v15.8.0

```

**Comment by kyrelldixon** [comment]
Thanks for reporting this @jet10000 ! I updated the docs to get a proper degit script. You can use `npx degit "kyrelldixon/svelte-tailwind-extension-boilerplate#main" your-extension-name` to make a copy of the project.
